server:
  port: 88
  servlet:
    context-path: /boot

spring:
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
  jackson:
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/weixin?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    password: guest
    username: guest
    publisher-returns: true
    publisher-confirm-type: correlated
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.mybatis.boot.model
#  configuration:
#    cache-enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.mybatis.boot.model
  configuration:
    cache-enabled: true

logging:
  level:
    com.mybatis.boot.mapper.*: debug

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

fdfs:
  tracker-list:
    - 192.168.171.128:22122
  connect-timeout: 600
  so-timeout: 1500
  thumb-image:
    width: 150
    height: 150
  web-server-url: http://192.168.171.128:88/

